# Generated by Django 4.2.4 on 2024-06-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='car/media/uploads/'),
        ),
    ]
