# Generated by Django 4.2.4 on 2024-06-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
    ]
