# Generated by Django 4.2.4 on 2024-06-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_rename_brand_name_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='brand_name',
        ),
    ]
