# Generated by Django 4.2.4 on 2024-06-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_remove_car_customer_car_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='customers',
        ),
    ]
